language: ruby
bundler_args: --without development

rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - jruby-9.1.5.0

sudo: false

# Gitter integration
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4d6749e48eb60321640e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
